spring.application.name=software213

spring.datasource.url=jdbc:mysql://localhost:3306/software213?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# \u2705 CAMBIO TEMPORAL: Cambiar 'update' por 'create-drop'
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect