package app.infrastructure.persistence.mapper;

import app.domain.model.Patient;
import app.domain.model.EmergencyContact;
import app.domain.model.Insurance;
import app.infrastructure.persistence.entities.PatientEntity;


public class PatientMapper {

    public static PatientEntity toEntity(Patient domain) {
        PatientEntity entity = new PatientEntity();
        entity.setId(null); // ID is autogenerated
        entity.setName(domain.getName());
        entity.setDocument(domain.getDocument());
        entity.setAge(domain.getAge());
        entity.setGender(domain.getGender());

        EmergencyContact contact = domain.getEmergencyContact();
        if (contact != null) {
            EmergencyContact ec = new EmergencyContact();
            ec.setName(contact.getName());
            ec.setPhone(contact.getPhone());
            ec.setRelationship(contact.getRelationship());
            entity.setEmergencyContact(ec);
        }

        Insurance insurance = domain.getInsurance();
        if (insurance != null) {
            Insurance ie = new Insurance();
            ie.setCompany(insurance.getCompany());
            ie.setPolicyNumber(insurance.getPolicyNumber());
            ie.setPolicyEndDate(insurance.getPolicyEndDate());
            entity.setInsurance(ie);
        }

        return entity;
    }

    public static Patient toDomain(PatientEntity entity) {
        Patient domain = new Patient();
        domain.setName(entity.getName());
        domain.setDocument(entity.getDocument());
        domain.setAge(entity.getAge());
        domain.setGender(entity.getGender());

        EmergencyContact ec = entity.getEmergencyContact();
        if (ec != null) {
            EmergencyContact contact = new EmergencyContact();
            contact.setName(ec.getName());
            contact.setPhone(ec.getPhone());
            contact.setRelationship(ec.getRelationship());
            domain.setEmergencyContact(contact);
        }

        Insurance ie = entity.getInsurance();
        if (ie != null) {
            Insurance insurance = new Insurance();
            insurance.setCompany(ie.getCompany());
            insurance.setPolicyNumber(ie.getPolicyNumber());
            insurance.setPolicyEndDate(ie.getPolicyEndDate());
            domain.setInsurance(insurance);
        }

        return domain;
    }
}
